version: "3.5"
services:
#  jaeger-all-in-one:
#    image: jaegertracing/all-in-one:latest
#    ports:
#      - "16686:16686"
#      - "14268"
#      - "14250"
    # Collector

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.37.0
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: ./prometheus/config.yml
        target: /etc/prometheus/prometheus.yml