global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'temporalmetrics java'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - 'host.docker.internal:8077'
        labels:
          group: 'sdk-metrics'



